parameters:
  database:
    defaultDatabase: db1
    db1:
      driver: pdo_pgsql
      dbname: database
      user: username
      password: password
      host: 127.0.0.1

services:
  G\Db:
    class: G\Db
    arguments: [%database%]